apps/articles/urls.py
from django.urls import path

import apps.articles.views as main_page

app_name = "articles"

urlpatterns = [
    path("", main_page.main_page, name="main_page"),
    path("all/", main_page.main_page, name="all_hubs"),
    path("<int:page>/", main_page.main_page, name="articles_page"),
    path("article/<int:pk>/", main_page.article, name="article"),
    path("hub/<int:pk>/", main_page.hub, name="hub"),
    path("hub/<int:pk>/<int:page>", main_page.hub, name="articles_hub_pag"),
    path("ajax/change_rate/", main_page.change_article_rate, name="ajax_change_rate"),
    path("ajax/rate_author/", main_page.like_dislike_author_ajax, name="ajax_rate_author"),
    path("author/<int:pk>/", main_page.show_author_profile, name="author_profile"),
    path('search/<int:page>/', main_page.search_articles, name='search_articles'),
    path("sorted_articles/<int:page>/", main_page.post_list, name='sorted_articles'),
    path("sorted_articles/<int:pk>/<int:page>/", main_page.post_list, name='sorted_articles_hub'),
    path("sorted_articles_user/<int:user_pk>/<int:page>/", main_page.post_list_user, name='sorted_articles_user'),
    path("sorted_articles_search/<int:page>/", main_page.post_list_search, name='sorted_articles_search'),
    path("notifications/viewed/all/", main_page.mark_all_as_viewed, name='all_viewed'),
    path("notifications/viewed/<str:target>/<int:pk>/", main_page.target_mark_as_viewed, name='target_viewed'),
]

habr/urls.py
from ckeditor_uploader.views import upload
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include

urlpatterns = [
    path("", include("apps.articles.urls", namespace="articles")),
    path("account/", include("apps.account.urls", namespace="account")),
    path("auth/", include("apps.authorization.urls", namespace="auth")),
    path("admin/", admin.site.urls, name="admin"),
    path("comments/", include("apps.comments.urls", namespace="comments")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("upload/", login_required(upload), name="ckeditor_upload"),
    path("", include("social_django.urls", namespace="social")),
    path("moderator/", include("apps.moderator.urls", namespace="moderator")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/articles/includes/sorted/sorted.html
{% load static %}

<nav class="sorted-menu">
    <form role="sorted" method="GET" id="form-sorted" data-url=
            "{% url 'articles:sorted_articles' 1 %}" style="display: block">
        <div class="btn-group mb-2" role="group" aria-label="Basic radio toggle button group">
            <input class="btn-check sorted-input" type="radio" name="sorted" value="-date" id="-date" autocomplete="off">
            <label class="btn btn-outline-secondary btn-sm"  for="-date">По дате</label>

            <input class="btn-check sorted-input" type="radio" name="sorted" value="like" id="like" autocomplete="off">
            <label class="btn btn-outline-secondary btn-sm" for="like">Рейтингу</label>

            <input class="btn-check sorted-input" type="radio" name="sorted" value="comments" id="comments" autocomplete="off">
            <label class="btn btn-outline-secondary btn-sm" for="comments">Комментам</label>

            <input class="btn-check sorted-input" type="radio" name="sorted" value="view" id="view" autocomplete="off">
            <label class="btn btn-outline-secondary btn-sm" for="view">Просмотрам</label>
        </div>
    </form>
</nav>

templates/articles/includes/sorted/sorted_hub.html
{% load static %}

<nav class="sorted-menu">
    <form role="sorted" method="GET" id="form-sorted" data-url=
            "{% url 'articles:sorted_articles_hub' pk 1 %}" style="display: block">
        <div class="btn-group mb-2" role="group" aria-label="Basic radio toggle button group">
            <input class="btn-check sorted-input" type="radio" name="sorted" value="-date" id="-date" autocomplete="off">
            <label class="btn btn-outline-secondary btn-sm"  for="-date">По дате</label>

            <input class="btn-check sorted-input" type="radio" name="sorted" value="like" id="like" autocomplete="off">
            <label class="btn btn-outline-secondary btn-sm" for="like">Рейтингу</label>

            <input class="btn-check sorted-input" type="radio" name="sorted" value="comments" id="comments" autocomplete="off">
            <label class="btn btn-outline-secondary btn-sm" for="comments">Комментам</label>

            <input class="btn-check sorted-input" type="radio" name="sorted" value="view" id="view" autocomplete="off">
            <label class="btn btn-outline-secondary btn-sm" for="view">Просмотрам</label>
        </div>
    </form>
</nav>

templates/articles/includes/sorted/sorted_search.html
{% load static %}

<nav class="sorted-menu">
    <form role="sorted" method="GET" id="form-sorted" data-url=
            "{% url 'articles:sorted_articles_search' 1 %}" style="display: block">
        <div class="btn-group mb-2" role="group" aria-label="Basic radio toggle button group">
            <input class="btn-check sorted-input" type="radio" name="sorted" value="-date" id="-date" autocomplete="off">
            <label class="btn btn-outline-secondary btn-sm"  for="-date">По дате</label>

            <input class="btn-check sorted-input" type="radio" name="sorted" value="like" id="like" autocomplete="off">
            <label class="btn btn-outline-secondary btn-sm" for="like">Рейтингу</label>

            <input class="btn-check sorted-input" type="radio" name="sorted" value="comments" id="comments" autocomplete="off">
            <label class="btn btn-outline-secondary btn-sm" for="comments">Комментам</label>

            <input class="btn-check sorted-input" type="radio" name="sorted" value="view" id="view" autocomplete="off">
            <label class="btn btn-outline-secondary btn-sm" for="view">Просмотрам</label>
        </div>
    </form>
</nav>