apps/articles/urls.py
from django.urls import path

import apps.articles.views as main_page

app_name = "articles"

urlpatterns = [
    path("", main_page.main_page, name="main_page"),
    path("all/", main_page.main_page, name="all_hubs"),
    path("<int:page>/", main_page.main_page, name="articles_page"),
    path("article/<int:pk>/", main_page.article, name="article"),
    path("hub/<int:pk>/", main_page.hub, name="hub"),
    path("hub/<int:pk>/<int:page>", main_page.hub, name="articles_hub_pag"),
    path("ajax/change_rate/", main_page.change_article_rate, name="ajax_change_rate"),
    path("ajax/rate_author/", main_page.like_dislike_author_ajax, name="ajax_rate_author"),
    path("author/<int:pk>/", main_page.show_author_profile, name="author_profile"),
    path('search/<int:page>/', main_page.search_articles, name='search_articles'),
    path("sorted_articles/<int:page>/", main_page.post_list, name='sorted_articles'),
    path("sorted_articles/<int:pk>/<int:page>/", main_page.post_list, name='sorted_articles_hub'),
    path("sorted_articles_user/<int:user_pk>/<int:page>/", main_page.post_list_user, name='sorted_articles_user'),
    path("sorted_articles_search/<int:page>/", main_page.post_list_search, name='sorted_articles_search'),
    path("notifications/viewed/all/", main_page.mark_all_as_viewed, name='all_viewed'),
    path("notifications/viewed/<str:target>/<int:pk>/", main_page.target_mark_as_viewed, name='target_viewed'),
]

apps/moderator/urls.py
from django.urls import path

import apps.moderator.views as moderator

app_name = "moderator"

urlpatterns = [
    path("complaints/", moderator.complaints, name="complaints"),
    path("review_articles/", moderator.review_articles, name='review_articles'),
    path("banned_users/", moderator.banned_users, name='banned_users'),
    path("add_user_ban/<int:pk>/", moderator.add_user_ban, name='add_user_ban'),
    path("remove_user_ban/<int:pk>/", moderator.remove_user_ban, name='remove_user_ban'),
    path("allow_publishing/<int:pk>/", moderator.allow_publishing, name='allow_publishing'),
    path("reject_publishing/<int:pk>/", moderator.reject_publishing, name='reject_publishing'),
    path("return_article/<int:pk>/", moderator.return_article, name='return_article'),
    path("complain_to_article/<int:pk>/", moderator.complain_to_article, name='complain_to_article'),
    path("complain_to_comment/<int:pk>/<int:pk_article>/", moderator.complain_to_comment, name='complain_to_comment'),
    path("send_complain_to_article/<int:pk>/", moderator.send_complain_to_article, name='send_complain_to_article'),
    path("send_complain_to_comment/<int:pk>/<int:pk_article>/", moderator.send_complain_to_comment, name='send_complain_to_comment'),
    path("ban_article/<int:pk>/", moderator.ban_article, name='ban_article'),
    path("no_ban_article/<int:pk>/", moderator.no_ban_article, name='no_ban_article'),
    path("ban_comment/<int:pk>/", moderator.ban_comment, name='ban_comment'),
    path("send_ban_comment/<int:pk>/", moderator.send_ban_comment, name='send_ban_comment'),
    path("no_ban_comment/<int:pk>/", moderator.no_ban_comment, name='no_ban_comment'),
]

habr/urls.py
from ckeditor_uploader.views import upload
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include

urlpatterns = [
    path("", include("apps.articles.urls", namespace="articles")),
    path("account/", include("apps.account.urls", namespace="account")),
    path("auth/", include("apps.authorization.urls", namespace="auth")),
    path("admin/", admin.site.urls, name="admin"),
    path("comments/", include("apps.comments.urls", namespace="comments")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("upload/", login_required(upload), name="ckeditor_upload"),
    path("", include("social_django.urls", namespace="social")),
    path("moderator/", include("apps.moderator.urls", namespace="moderator")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/moderator/forms.py
from django import forms

from apps.moderator.models import BannedUser, VerifyArticle, ComplainToComment


class BannedUserForm(forms.ModelForm):
    class Meta:
        model = BannedUser
        exclude = ('offender', 'date_ban', 'is_active')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'is_forever':
                field.widget.attrs["class"] = "checkbox-field"
            else:
                field.widget.attrs["class"] = "form-control"
            field.help_text = ""


class RemarkCreateForm(forms.ModelForm):
    class Meta:
        model = VerifyArticle
        fields = ('remark',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class ComplainCreateForm(forms.ModelForm):
    class Meta:
        model = ComplainToComment
        fields = ('text_complain',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class ReasonCreateForm(forms.ModelForm):
    class Meta:
        model = ComplainToComment
        fields = ('text_reason',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"

apps/moderator/views.py
from datetime import datetime
from smtplib import SMTPDataError

from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from apps.authorization.models import HabrUser
from apps.moderator.forms import BannedUserForm, RemarkCreateForm, \
    ComplainCreateForm, ReasonCreateForm
from apps.moderator.models import BannedUser, VerifyArticle, \
    ComplainToArticle, ComplainToComment


def complaints(request):
    title = "Жалобы"
    complaints_to_article = ComplainToArticle.get_all_complaints()
    complaints_to_comments = ComplainToComment.get_all_complaints()
    page_data = {
        "title": title,
        "articles": complaints_to_article,
        "comments": complaints_to_comments,
    }
    return render(request, "moderator/complaints.html", page_data)


def review_articles(request):
    """получение всех статей на проверку"""
    articles = VerifyArticle.get_all_articles_for_verifications()
    title = "Статьи на проверку"
    page_data = {
        "title": title,
        "articles": articles,
    }
    return render(request, "moderator/review_articles.html", page_data)


def add_user_ban(request, pk):
    title = "Блокирование пользователя"
    current_user = HabrUser.objects.get(pk=pk)

    if request.method == 'POST':
        ban_form = BannedUserForm(request.POST)
        if ban_form.is_valid():
            banned_user_query = BannedUser.objects.filter(offender=pk)
            if banned_user_query:
                banned_user = banned_user_query[0]
                banned_user.is_active = True
                banned_user.reason = request.POST["reason"]
                if request.POST.get("is_forever"):
                    banned_user.is_forever = True
                else:
                    banned_user.is_forever = False
                banned_user.num_days = request.POST["num_days"]
                banned_user.date_ban = datetime.today()
                banned_user.save()
            else:
                banned_user = BannedUser.objects.create(
                    offender=current_user,
                    reason=request.POST["reason"],
                    num_days=request.POST["num_days"],
                    is_active=True,
                    is_forever=True if request.POST.get("is_forever")
                    else False
                )
            try:
                banned_user.set_ban_email()
            except SMTPDataError:
                pass
            return HttpResponseRedirect(reverse("articles:author_profile",
                                                args=[pk]))
        else:
            messages.error(request, 'ошибка')
    else:
        ban_form = BannedUserForm()
    page_data = {
        "title": title,
        "ban_form": ban_form,
        "current_user_pk": pk,
    }
    return render(request, 'moderator/add_ban.html', page_data)


def remove_user_ban(request, pk):
    current_user = BannedUser.objects.get(offender=pk)
    current_user.delete()
    try:
        current_user.unset_ban_email()
    except SMTPDataError:
        pass
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


# def remove_user_ban(request, pk):
#     if request.is_ajax():
#         current_user = BannedUser.objects.get(offender=pk)
#         current_user.delete()
#         content = {
#             'current_user': current_user,
#             'user': request.user,
#         }
#         # result = render_to_string('moderator/includes/ban_buttons.html', content)
#         result = render_to_string('articles/author_profile.html', content)
#         return JsonResponse({'result': result})


def banned_users(request):
    title = "Заблокированные пользователи"
    banned_users_query = BannedUser.objects.filter(is_active=True)
    page_data = {
        "title": title,
        "banned_users": banned_users_query
    }
    return render(request, "moderator/banned_users.html", page_data)


def allow_publishing(request, pk):
    """Разрешение модератором публикации статьи"""
    VerifyArticle.allow_publishing(pk)
    return HttpResponseRedirect(reverse('moderator:review_articles'))


def reject_publishing(request, pk):
    """Отказ модератором на публикацию статьи"""
    form_remark = RemarkCreateForm(request.POST or None)
    page_data = {
        "pk": pk,
        "form_remark": form_remark,
    }
    return render(request, 'moderator/form_return_article.html', page_data)


def return_article(request, pk):
    """отправка на доработку и с обязательной причиной отказа"""
    if request.method == 'POST':
        form_remark = RemarkCreateForm(request.POST or None)
        if form_remark.is_valid():
            VerifyArticle.return_article(request.POST["remark"], pk)
    else:
        form_remark = RemarkCreateForm()
    return HttpResponseRedirect(reverse("moderator:review_articles"))


def complain_to_article(request, pk):
    """Жалоба на статью"""
    form_complain = ComplainCreateForm(request.POST or None)
    page_data = {
        "pk": pk,
        "form_complain": form_complain,
    }
    return render(request, 'moderator/form_complain_article.html',
                  page_data)


def complain_to_comment(request, pk, pk_article=None):
    """Жалоба на комментарий"""
    form_complain = ComplainCreateForm(request.POST or None)
    page_data = {
        "pk": pk,
        "form_complain": form_complain,
        "pk_article": pk_article,
    }
    return render(request, 'moderator/form_complain_comment.html',
                  page_data)


def send_complain_to_article(request, pk):
    """отправка жалобы на статью на модерацию"""
    if request.method == 'POST':
        form_complain = ComplainCreateForm(request.POST or None)
        if form_complain.is_valid():
            ComplainToArticle.send_complain_to_article(
                pk,
                request.POST["text_complain"],
                request.user.pk
            )
    else:
        form_complain = ComplainCreateForm()
    return HttpResponseRedirect(reverse("articles:article",
                                                args=[pk]))


def send_complain_to_comment(request, pk, pk_article=None):
    """отправка жалобы на комментарий на модерацию"""
    if request.method == 'POST':
        form_complain = ComplainCreateForm(request.POST or None)
        if form_complain.is_valid():
            ComplainToComment.send_complain_to_comment(
                pk,
                request.POST["text_complain"],
                request.user.pk
            )
    else:
        form_complain = ComplainCreateForm()
    if pk_article is None:
        return HttpResponseRedirect(reverse("articles:main_page"))
    return HttpResponseRedirect(reverse("articles:article",
                                        args=[pk_article]))


def ban_article(request, pk):
    ComplainToArticle.reject_article(pk)
    return HttpResponseRedirect(reverse("moderator:complaints"))


def no_ban_article(request, pk):
    ComplainToArticle.allow_article(pk)
    return HttpResponseRedirect(reverse("moderator:complaints"))


def ban_comment(request, pk):
    form_reason = ReasonCreateForm(request.POST or None)
    page_data = {
        "pk": pk,
        "form_reason": form_reason,
    }
    return render(request, 'moderator/form_reason_ban_comment.html',
                  page_data)


def send_ban_comment(request, pk):
    ComplainToComment.reject_comment(pk)
    if request.method == 'POST':
        form_reason = ReasonCreateForm(request.POST or None)
        if form_reason.is_valid():
            ComplainToComment.objects.filter(pk=pk).update(
                text_reason=request.POST["text_reason"]
            )
    else:
        form_reason = ReasonCreateForm()
    return HttpResponseRedirect(reverse("moderator:complaints"))


def no_ban_comment(request, pk):
    ComplainToComment.allow_comment(pk)
    return HttpResponseRedirect(reverse("moderator:complaints"))

templates/moderator/add_ban.html
{% extends 'moderator/base.html' %}
{% load my_tags %}
{% block content %}
        <h1 style="text-align:center">Блокирование пользователя</h1>
        <form class="auth-form" action="{% url 'moderator:add_user_ban' current_user_pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ ban_form.as_table }}
            <br>
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
        <div style="text-align: center; margin-top: 15px;">
            <a href="{% url 'articles:author_profile' current_user_pk %}"><button style="width:300px" type="reset" class="btn btn-danger">Назад</button></a>
        </div>
{% endblock content %}

templates/moderator/banned_users.html
{% extends 'moderator/base.html' %}
{% load my_tags %}
{% block content %}
    {% include 'moderator/includes/inc_menu.html' %}
    <div class='string__container moder-string'>
        <div class="moder-article-row" style="min-height: 35px !important; font-weight: 500">
            <div class="col-lg-1 bord mobile-hide">№</div>
            <div class="col-lg-3 col-4 bord">Имя</div>
            <div class="col-lg-2 mobile-hide bord">Дата блокировки</div>
            <div class="col-lg-4 col-5 bord">Причина</div>
            <div class="col-lg-2 col-3 bord">Дней до снятия</div>
        </div>
        {% for user in banned_users %}
            <div class="bookmark__row" style="min-height: 60px !important;">
                <div class="col-lg-1 bord mobile-hide">
                    {{ forloop.counter }}
                </div>
                <div class="col-lg-3 col-4 bord" style="font-weight: 700">
                    <a href="{% url 'articles:author_profile' user.offender.pk %}">{{ user.offender.username }}</a>
                </div>
                <div class="col-lg-2 mobile-hide bord">{{ user.date_ban }}</div>
                <div class="col-lg-4 col-5 bord">{{ user.reason|truncatechars:35 }}</div>
                {% if user.is_forever %}
                    <div class="col-lg-2 col-3 bord">Бессрочно</div>
                {% else %}
                    <div class="col-lg-2 col-3 bord">{{ user.get_remaining_days }}</div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock content %}
    {#    <table class="table">#}
    {#        <thead class="thead-dark">#}
    {#        <tr>#}
    {#            <th scope="col">№</th>#}
    {#            <th scope="col">Имя пользователя</th>#}
    {#            <th scope="col">Дата блокировки</th>#}
    {#            <th scope="col">Причина блокировки</th>#}
    {#            <th scope="col">Оставшихся дней блокировки</th>#}
    {#        </tr>#}
    {#        </thead>#}
    {#        <tbody>#}
    {#        {% for user in banned_users %}#}
    {#            <tr>#}
    {#                <th scope="row">{{ forloop.counter }}</th>#}
    {#                <td><a href="{% url 'articles:author_profile' user.pk %}">{{ user.offender.username }}</a></td>#}
    {#                <td>{{ user.date_ban }}</td>#}
    {#                <td>{{ user.reason }}</td>#}
    {#                {% if user.is_forever %}#}
    {#                    <td>Бессрочно</td>#}
    {#                {% else %}#}
    {#                    <td>{{ user.get_remaining_days }}</td>#}
    {#                {% endif %}#}
    {#                <td>#}
    {#                    <button class="btn btn-link btn-unlock">#}
    {#                        <a href="{% url 'moderator:remove_user_ban' user.offender_id %}">Разблокировать</a>#}
    {#                    </button>#}
    {#                </td>#}
    {#            </tr>#}
    {#        {% endfor %}#}
    {#        </tbody>#}
    {#    </table>#}

templates/moderator/base.html
{% extends 'articles/base.html' %}

templates/moderator/complaints.html
{% extends 'moderator/base.html' %}
{% load my_tags %}
{% block content %}
    {% include 'moderator/includes/inc_menu.html' %}
    <div class='string__container moder-string'>
        <div class="moder-article-row" style="min-height: 35px !important; font-weight: 500">
            <div class="col-lg-3 col-4 bord">Объект</div>
            <div class="col-lg-3 col-4 bord">Текст жалобы</div>
            <div class="col-lg-2 mobile-hide bord">Жалоба на</div>
            <div class="col-lg-2 mobile-hide bord">Жалоба от</div>
            <div class="col-lg-2 col-4 bord">Создана</div>
        </div>
        {% for article in articles %}
            <a href="{% url 'articles:article' article.article.id %}" class="bookmark__row"
               style="min-height: 60px !important;">
                <div class="col-lg-3 col-4 bord"><span
                        style="font-weight: 700">Статья</span>: {{ article.article.title|truncatechars:45 }}</div>
                <div class="col-lg-3 col-4 bord"
                     title="{{ article.text_complain }}">{{ article.text_complain|truncatechars:60 }}</div>
                <div class="col-lg-2 mobile-hide bord">
                    <p style="font-weight: 700; margin: 0">{{ article.article.author }}</p>
                </div>
                <div class="col-lg-2 mobile-hide bord">{{ article.user }}</div>
                <div class="col-lg-2 col-4 bord">{{ article.created }}</div>
            </a>
        {% endfor %}
        {% for comment in comments %}
            {#     ссылка на якорь      #}
            <a href="{% url 'articles:article' comment.comment.article.id %}#id{{ comment.comment.id }}" class="bookmark__row"
               style="min-height: 60px !important;">
                <div class="col-lg-3 col-4 bord"><span
                        style="font-weight: 700">Коммент</span>: {{ comment.comment|truncatechars:45 }}</div>
                <div title="{{ comment.text_complain }}" class="col-lg-3 col-4 bord">{{ comment.text_complain|truncatechars:60 }}</div>
                <div class="col-lg-2 mobile-hide bord">
                    <p style="font-weight: 700; margin: 0">{{ comment.comment.author }}</p>
                </div>
                <div class="col-lg-2 mobile-hide bord">{{ comment.user }}</div>
                <div class="col-lg-2 col-4 bord">{{ comment.created }}</div>
            </a>
        {% endfor %}
    </div>
{% endblock content %}


{#    <div class='string__container'>#}
{#        <div class="bookmark__row col-12">#}
{#            <div class="col-6 bord">Объект жалобы</div>#}
{#            <div class="col-2 bord">Автор объекта</div>#}
{#            <div class="col-2 bord">Отправитель</div>#}
{#            <div class="col-1 bord">Создана</div>#}
{#        </div>#}
{#    </div>#}
{#    {% include 'moderator/includes/inc_complaints_string_output.html' %}#}

templates/moderator/form_complain_article.html
{% extends 'moderator/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="complains">
        <div style="max-width: 400px">
            <h1 style="text-align: center">Причина жалобы на статью</h1>
            <br>
            <form class="" action="{% url 'moderator:send_complain_to_article' pk %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ form_complain.as_p }}
                <br>
                <div style="display: flex; justify-content: space-around">
                    <div>
                        <a href="#">
                            <button style="width:104px" type="reset" class="btn btn-danger">Назад</button>
                        </a>
                    </div>
                    <div>
                        <input type="submit" value="Отправить" class="btn btn-outline-success">
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

templates/moderator/form_complain_comment.html
{% extends 'moderator/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="complains">
        <div style="max-width: 400px">
            <h1 style="text-align: center">Причина жалобы на комментарий</h1>
            <br>
            <form class="" action="{% url 'moderator:send_complain_to_comment' pk pk_article %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ form_complain.as_p }}
                <br>
                <div style="display: flex; justify-content: space-around">
                    <div>
                        <a href="#">
                            <button style="width:104px" type="reset" class="btn btn-danger">Назад</button>
                        </a>
                    </div>
                    <div>
                        <input type="submit" value="Отправить" class="btn btn-outline-success">
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

templates/moderator/form_reason_ban_comment.html
{% extends 'moderator/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="complains">
        <div style="max-width: 400px">
            <h1 style="text-align: center">Причина бана комментария</h1>
            <br>
            <form class="" action="{% url 'moderator:send_ban_comment' pk %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ form_reason.as_p }}
                <br>
                <div style="display: flex; justify-content: space-around">
                    <div>
                        <a href="#">
                            <button style="width:104px" type="reset" class="btn btn-danger">Назад</button>
                        </a>
                    </div>
                    <div>
                        <input type="submit" value="Отправить" class="btn btn-outline-success">
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

templates/moderator/form_return_article.html
{% extends 'moderator/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="complains">
        <div style="max-width: 400px">
            <h1 style="text-align: center">Комментарий для возврата статьи на доработку</h1>
            <br>
            <form class="" action="{% url 'moderator:return_article' pk %}" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ form_remark.as_p }}
                <br>
                <div style="display: flex; justify-content: space-around">
                    <div>
                        <a href="#">
                            <button style="width:104px" type="reset" class="btn btn-danger">Назад</button>
                        </a>
                    </div>
                    <div>
                        <input type="submit" value="Отправить" class="btn btn-outline-success">
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

templates/moderator/review_articles.html
{% extends 'moderator/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
    {% include 'moderator/includes/inc_menu.html' %}
    <div class='string__container'>
        <div class="moder-article-row" style="min-height: 35px !important; font-weight: 500">
            <div class="col-lg-2 col-4 bord">Создана</div>
            <div class="col-4 bord">Статья</div>
            <div class="col-lg-2 col-4 bord">Автор</div>
            <div class="col-lg-3 mobile-hide bord">Хаб</div>
            <div class="col-lg-1 mobile-hide">Картинка</div>
        </div>
    </div>
    {% include 'moderator/includes/inc_articles_string_output.html' %}
{% endblock content %}