apps/articles/urls.py
from django.urls import path

import apps.articles.views as main_page

app_name = "articles"

urlpatterns = [
    path("", main_page.main_page, name="main_page"),
    path("all/", main_page.main_page, name="all_hubs"),
    path("<int:page>/", main_page.main_page, name="articles_page"),
    path("article/<int:pk>/", main_page.article, name="article"),
    path("hub/<int:pk>/", main_page.hub, name="hub"),
    path("hub/<int:pk>/<int:page>", main_page.hub, name="articles_hub_pag"),
    path("ajax/change_rate/", main_page.change_article_rate, name="ajax_change_rate"),
    path("ajax/rate_author/", main_page.like_dislike_author_ajax, name="ajax_rate_author"),
    path("author/<int:pk>/", main_page.show_author_profile, name="author_profile"),
    path('search/<int:page>/', main_page.search_articles, name='search_articles'),
    path("sorted_articles/<int:page>/", main_page.post_list, name='sorted_articles'),
    path("sorted_articles/<int:pk>/<int:page>/", main_page.post_list, name='sorted_articles_hub'),
    path("sorted_articles_user/<int:user_pk>/<int:page>/", main_page.post_list_user, name='sorted_articles_user'),
    path("sorted_articles_search/<int:page>/", main_page.post_list_search, name='sorted_articles_search'),
    path("notifications/viewed/all/", main_page.mark_all_as_viewed, name='all_viewed'),
    path("notifications/viewed/<str:target>/<int:pk>/", main_page.target_mark_as_viewed, name='target_viewed'),
]

apps/authorization/urls.py
from django.urls import path

import apps.authorization.views as auth

app_name = "auth"

urlpatterns = [
    path("login/", auth.login, name="login"),
    path("register/", auth.register, name="register"),
    path("logout/", auth.logout, name="logout"),
    path("forgive/", auth.forgive, name="forgive"),
    path("verify/<email>/<activation_key>/", auth.verify, name='verify'),
    path("send/<pk>/", auth.send_repeat_email, name='send'),
]

apps/comments/urls.py
from django.urls import path

import apps.comments.views as comments

from .apps import CommentsConfig

app_name = CommentsConfig.name

urlpatterns = [
    path("create/<int:pk>", comments.comment_create, name="comment_create"),
    path("create-child/<int:pk>/<int:id_parent_comment>",
         comments.child_comment_create, name="comment_child_create"),
    path("ajax/like", comments.like_dislike_ajax, name="ajax_comment"),
]

apps/moderator/urls.py
from django.urls import path

import apps.moderator.views as moderator

app_name = "moderator"

urlpatterns = [
    path("complaints/", moderator.complaints, name="complaints"),
    path("review_articles/", moderator.review_articles, name='review_articles'),
    path("banned_users/", moderator.banned_users, name='banned_users'),
    path("add_user_ban/<int:pk>/", moderator.add_user_ban, name='add_user_ban'),
    path("remove_user_ban/<int:pk>/", moderator.remove_user_ban, name='remove_user_ban'),
    path("allow_publishing/<int:pk>/", moderator.allow_publishing, name='allow_publishing'),
    path("reject_publishing/<int:pk>/", moderator.reject_publishing, name='reject_publishing'),
    path("return_article/<int:pk>/", moderator.return_article, name='return_article'),
    path("complain_to_article/<int:pk>/", moderator.complain_to_article, name='complain_to_article'),
    path("complain_to_comment/<int:pk>/<int:pk_article>/", moderator.complain_to_comment, name='complain_to_comment'),
    path("send_complain_to_article/<int:pk>/", moderator.send_complain_to_article, name='send_complain_to_article'),
    path("send_complain_to_comment/<int:pk>/<int:pk_article>/", moderator.send_complain_to_comment, name='send_complain_to_comment'),
    path("ban_article/<int:pk>/", moderator.ban_article, name='ban_article'),
    path("no_ban_article/<int:pk>/", moderator.no_ban_article, name='no_ban_article'),
    path("ban_comment/<int:pk>/", moderator.ban_comment, name='ban_comment'),
    path("send_ban_comment/<int:pk>/", moderator.send_ban_comment, name='send_ban_comment'),
    path("no_ban_comment/<int:pk>/", moderator.no_ban_comment, name='no_ban_comment'),
]

habr/urls.py
from ckeditor_uploader.views import upload
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include

urlpatterns = [
    path("", include("apps.articles.urls", namespace="articles")),
    path("account/", include("apps.account.urls", namespace="account")),
    path("auth/", include("apps.authorization.urls", namespace="auth")),
    path("admin/", admin.site.urls, name="admin"),
    path("comments/", include("apps.comments.urls", namespace="comments")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("upload/", login_required(upload), name="ckeditor_upload"),
    path("", include("social_django.urls", namespace="social")),
    path("moderator/", include("apps.moderator.urls", namespace="moderator")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/comments/forms.py
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django import forms
from django.forms import CharField

from apps.comments.models import Comment


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("body",)


# class CommentCreateForm(forms.ModelForm):
#     body = CharField(label='Комментарий', widget=CKEditorUploadingWidget(config_name="for_user"))
#
#     class Meta:
#         model = Comment
#         fields = ("body",)

apps/comments/views.py
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import HttpResponseRedirect, get_object_or_404
from django.http import JsonResponse
from django.forms.models import model_to_dict
from django.conf import settings
from django.template.loader import render_to_string

from apps.articles.models import Article, Hub
from .forms import CommentCreateForm
from .models import Comment


@login_required
@transaction.atomic
def comment_create(request, pk):
    current_article = get_object_or_404(Article, id=pk)
    form_comment = CommentCreateForm(request.POST or None)
    if request.method == 'POST':
        if form_comment.is_valid():
            new_comment = form_comment.save(commit=False)
            new_comment.author = request.user
            new_comment.article = current_article
            new_comment.body = form_comment.cleaned_data["body"]
            new_comment.parent = None
            new_comment.is_child = False
            new_comment.save()
            #если в js стоит функция location.reload();, то return JsonResponse не нужен
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


@login_required
@transaction.atomic
def child_comment_create(request, pk, id_parent_comment):
    current_article = get_object_or_404(Article, id=pk)
    form_comment = CommentCreateForm(request.POST or None)
    if request.method == 'POST':
        if form_comment.is_valid():
            new_comment = form_comment.save(commit=False)
            new_comment.author = request.user
            new_comment.article = current_article
            new_comment.body = form_comment.cleaned_data["body"]
            new_comment.parent = Comment.get_comment(id_parent_comment)
            new_comment.is_child = True
            new_comment.save()
            #если в js стоит функция location.reload();, то return JsonResponse не нужен
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


def like_dislike_ajax(request):
    if request.is_ajax() and request.user.is_authenticated:
        field = request.GET.get("field")
        comment = request.GET.get("comment").split("-")[1]
        comment = Comment.objects.get(pk=comment)
        if request.user != comment.author:
            if field == "like":
                if comment.likes.filter(pk=request.user.pk).exists():
                    comment.likes.remove(request.user)
                    comment.author.habruserprofile.rating -= 1 * 0.5
                elif comment.dislikes.filter(pk=request.user.pk).exists():
                    comment.likes.add(request.user)
                    comment.dislikes.remove(request.user)
                    comment.author.habruserprofile.rating += 2 * 0.5
                else:
                    comment.likes.add(request.user)
                    comment.author.habruserprofile.rating += 1 * 0.5
            elif field == "dislike":
                if comment.dislikes.filter(pk=request.user.pk).exists():
                    comment.dislikes.remove(request.user)
                    comment.author.habruserprofile.rating += 1 * 0.5
                elif comment.likes.filter(pk=request.user.pk).exists():
                    comment.dislikes.add(request.user)
                    comment.likes.remove(request.user)
                    comment.author.habruserprofile.rating -= 2 * 0.5
                else:
                    comment.dislikes.add(request.user)
                    comment.author.habruserprofile.rating -= 1 * 0.5
            comment.author.habruserprofile.save()
        return JsonResponse(
            {
                "id": comment.pk,
                "likes": comment.likes.count(),
                "dislikes": comment.dislikes.count(),
                "like": comment.likes.filter(pk=request.user.pk).exists(),
                "dislike": comment.dislikes.filter(pk=request.user.pk).exists(),
            }
        )

templates/comments/comments.html
{% load static %}
{% load my_tags %}

<div class="comment-row" id="commentArticle">
    <h2 class="mb-4">({{ comments.count }}) Комментарии</h2>
    <ul class="comment-start" style="list-style-type:none;">
        <div class="col-md-12 mt-2" id="CommentList">
            {% for comment in comments %}
                {% if comment.parent == Null %}
                    {#     якорь      #}
                    <span id="id{{ comment.id }}"></span>
                    <li class="li-reply-comment">
                        <div class="main-comment-section col-md-12" id='CommentId-{{ comment.id }}'>
                            <div>
                                <div style="display: inline-block"><a
                                        href="{% url 'articles:author_profile' comment.author.id %}"
                                        class="post-author comment-author">
                                    <img src="{{ comment.author.habruserprofile.avatar|media_folder_users }}"
                                         alt=""/>
                                    <small>{{ comment.author }}</small>
                                </a></div>
                                <div style="display: inline-block"><span>{{ comment.date }}</span></div>
                                {#                                <div style="display: inline-block">#}
                                {#                                    <a title="Ссылка на данный комментарий #{{ comment.id }}" style="color: #192801"#}
                                {#                                       href="#id{{ comment.id }}">  < --#}
                                {#                                        <img src="{% static 'svg/arrow-address-back_icon-icons.com_54065.svg' %}" alt="">#}
                                {#                                    </a>#}
                                {#                                </div>#}
                            </div>
                            <div class="comment-text">
                                {% if comment.is_active %}
                                    <div>{{ comment.body }}</div>
                                {% else %}
                                    <div>
                                        <h6 style="color: darkred">Комментарий удалён модератором</h6>
                                        <span style="color: #6c6c6c">
                                            {{ comment.related_comment.all.0.text_reason|truncatechars:60 }}</span>
                                    </div>
                                {% endif %}
                            </div>
                            <span class='reply reply-comment' data-id="{{ comment.id }}">Ответить</span>
                            <form method="POST" class="comment-form" id="createChildCommentForm-{{ comment.id }}"
                                  data-url="{% url 'comments:comment_child_create' pk=article.id id_parent_comment=comment.id %}"
                                  style="display:none;">
                                {% csrf_token %}
                                {{ form_comment.as_p }}
                                {% if request.user.is_authenticated %}
                                    <button type="button" data-id="{{ comment.id }}"
                                            class="btn btn-outline-success createCommentChildBtn">Отправить
                                    </button>
                                {% else %}
                                    <button class="btn btn-outline-success"><a
                                            href="{% url 'auth:login' %}">Отправить</a></button>
                                {% endif %}
                                {#         <button type="button" data-id="{{ comment.id }}"#}
                                {#             class="btn btn-outline-success createCommentChildBtn">Отправить#}
                                {#         </button>#}
                            </form>
                            <div class="post-status">
                                {% if comment.id in comments_is_liked %}
                                    <img src="{% static 'svg/like(filled).svg' %}" alt="" id="like-{{ comment.id }}"
                                         class="comment_like"/>
                                {% else %}
                                    <img src="{% static 'svg/like.svg' %}" alt="" id="like-{{ comment.id }}"
                                         class="comment_like"/>
                                {% endif %}
                                <small class="green" id="likes{{ comment.id }}">{{ comment.likes.count }}</small>
                                {% if comment.id in comments_is_disliked %}
                                    <img src="{% static 'svg/dislike(filled).svg' %}" alt=""
                                         id="dislike-{{ comment.id }}" class="comment_dislike"/>
                                {% else %}
                                    <img src="{% static 'svg/dislike.svg' %}" alt="" id="dislike-{{ comment.id }}"
                                         class="comment_dislike"/>
                                {% endif %}
                                <small class="red" id="dislikes{{ comment.id }}">{{ comment.dislikes.count }}</small>

                                <!-- Начало блока статуса жалобы -->
                                {% if comment.id == comment.related_comment.all.0.comment_id %}
                                    {% for foo in comment.related_comment.all %}
                                        {% if foo.status == None %}
                                            <div>
                                                <div style="margin-left: 5px; display: flex; color: #990000">
                                                    <img src="{% static 'svg/complaints_push.svg' %}" alt=""/>
                                                    <div style="font-size: 13px">Жалоба оставлена</div>
                                                </div>
                                            </div>

                                            <!-- Начало блока жалобы для модератора -->
                                            {% if is_moderator %}
                                                <hr>
                                                <div class="moderator-block">
                                                    <div class="mt-4 mb-2">
                                                        <h5>Блок модератора</h5>
                                                    </div>
                                                    <div style="text-align: center">
                                                        <h6 style="opacity: 0.7">жалоба:</h6>
                                                        <div CLASS="moderator-text-compl">
                                                            {{ comment.related_comment.all.0.text_complain|truncatechars:300 }}
                                                        </div>
                                                    </div>
                                                    <div class="moderator-block-buttons mt-1">
                                                        <div>
                                                            <a class="btn btn-sm mt-1 bcgrnd_green" title=""
                                                               href="{% url 'moderator:no_ban_comment' comment.related_comment.all.0.id %}">Отклонить
                                                            </a>
                                                        </div>
                                                        <div>
                                                            <a class="btn btn-sm mt-1 bcgrnd_red" title=""
                                                               href="{% url 'moderator:ban_comment' comment.related_comment.all.0.id %}">Забанить
                                                            </a>
                                                        </div>
                                                    </div>
                                                </div>
                                                <hr>
                                            {% endif %}
                                            <!-- Конец блока жалобы для модератора -->

                                        {% elif foo.status == False %}
                                            <!-- Начало блока кнопки жалобы -->
                                            {% if request.user.is_authenticated %}
                                                <div style="margin-top: -6px">
                                                    <button type="button" data-toggle="modal"
                                                            title="Жалоба на комментарий"
                                                            data-target="#art-complain-com-modal"
                                                            style="border: none; background: none">
                                                        <img src="{% static 'svg/complaints.svg' %}" alt=""/>
                                                    </button>
                                                </div>
                                                {% include 'articles/includes/modals/comment_complain.html' %}
                                            {% endif %}
                                            <!-- Конец блока кнопки жалобы -->
                                        {% endif %}
                                    {% endfor %}
                                {% else %}
                                    <!-- Начало блока кнопки жалобы -->
                                    {% if request.user.is_authenticated %}
                                        <div style="margin-top: -6px">
                                            <button type="button" data-toggle="modal" title="Жалоба на комментарий"
                                                    data-target="#art-complain-com-modal"
                                                    style="border: none; background: none">
                                                <img src="{% static 'svg/complaints.svg' %}" alt=""/>
                                            </button>
                                        </div>
                                        {% include 'articles/includes/modals/comment_complain.html' %}
                                    {% endif %}
                                    <!-- Конец блока кнопки жалобы -->
                                {% endif %}
                                <!-- Конец блока статуса жалобы -->


                            </div>
                            {% include 'comments/includes/inc_tree_comments.html' %}
                        </div>
                    </li>
                {% endif %}
            {% endfor %}
        </div>
    </ul>
</div>
<div class="container-fluid mt-2">
    <form method="POST" class="comment-form" id="createCommentForm"
          data-url="{% url 'comments:comment_create' pk=article.id %}">
        {% csrf_token %}
        {{ form_comment.as_p }}
        {% if request.user.is_authenticated %}
            <button type="button" id="createCommentBtn" class="btn btn-outline-success">Отправить</button>
        {% else %}
            <button class="btn btn-outline-success"><a
                    href="{% url 'auth:login' %}">Отправить</a></button>
        {% endif %}
        {#        <button type="button" id="createCommentBtn" class="btn btn-outline-success">Отправить</button>#}
    </form>
</div>