apps/articles/urls.py
from django.urls import path

import apps.articles.views as main_page

app_name = "articles"

urlpatterns = [
    path("", main_page.main_page, name="main_page"),
    path("all/", main_page.main_page, name="all_hubs"),
    path("<int:page>/", main_page.main_page, name="articles_page"),
    path("article/<int:pk>/", main_page.article, name="article"),
    path("hub/<int:pk>/", main_page.hub, name="hub"),
    path("hub/<int:pk>/<int:page>", main_page.hub, name="articles_hub_pag"),
    path("ajax/change_rate/", main_page.change_article_rate, name="ajax_change_rate"),
    path("ajax/rate_author/", main_page.like_dislike_author_ajax, name="ajax_rate_author"),
    path("author/<int:pk>/", main_page.show_author_profile, name="author_profile"),
    path('search/<int:page>/', main_page.search_articles, name='search_articles'),
    path("sorted_articles/<int:page>/", main_page.post_list, name='sorted_articles'),
    path("sorted_articles/<int:pk>/<int:page>/", main_page.post_list, name='sorted_articles_hub'),
    path("sorted_articles_user/<int:user_pk>/<int:page>/", main_page.post_list_user, name='sorted_articles_user'),
    path("sorted_articles_search/<int:page>/", main_page.post_list_search, name='sorted_articles_search'),
    path("notifications/viewed/all/", main_page.mark_all_as_viewed, name='all_viewed'),
    path("notifications/viewed/<str:target>/<int:pk>/", main_page.target_mark_as_viewed, name='target_viewed'),
]

apps/authorization/urls.py
from django.urls import path

import apps.authorization.views as auth

app_name = "auth"

urlpatterns = [
    path("login/", auth.login, name="login"),
    path("register/", auth.register, name="register"),
    path("logout/", auth.logout, name="logout"),
    path("forgive/", auth.forgive, name="forgive"),
    path("verify/<email>/<activation_key>/", auth.verify, name='verify'),
    path("send/<pk>/", auth.send_repeat_email, name='send'),
]

apps/moderator/urls.py
from django.urls import path

import apps.moderator.views as moderator

app_name = "moderator"

urlpatterns = [
    path("complaints/", moderator.complaints, name="complaints"),
    path("review_articles/", moderator.review_articles, name='review_articles'),
    path("banned_users/", moderator.banned_users, name='banned_users'),
    path("add_user_ban/<int:pk>/", moderator.add_user_ban, name='add_user_ban'),
    path("remove_user_ban/<int:pk>/", moderator.remove_user_ban, name='remove_user_ban'),
    path("allow_publishing/<int:pk>/", moderator.allow_publishing, name='allow_publishing'),
    path("reject_publishing/<int:pk>/", moderator.reject_publishing, name='reject_publishing'),
    path("return_article/<int:pk>/", moderator.return_article, name='return_article'),
    path("complain_to_article/<int:pk>/", moderator.complain_to_article, name='complain_to_article'),
    path("complain_to_comment/<int:pk>/<int:pk_article>/", moderator.complain_to_comment, name='complain_to_comment'),
    path("send_complain_to_article/<int:pk>/", moderator.send_complain_to_article, name='send_complain_to_article'),
    path("send_complain_to_comment/<int:pk>/<int:pk_article>/", moderator.send_complain_to_comment, name='send_complain_to_comment'),
    path("ban_article/<int:pk>/", moderator.ban_article, name='ban_article'),
    path("no_ban_article/<int:pk>/", moderator.no_ban_article, name='no_ban_article'),
    path("ban_comment/<int:pk>/", moderator.ban_comment, name='ban_comment'),
    path("send_ban_comment/<int:pk>/", moderator.send_ban_comment, name='send_ban_comment'),
    path("no_ban_comment/<int:pk>/", moderator.no_ban_comment, name='no_ban_comment'),
]

habr/urls.py
from ckeditor_uploader.views import upload
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include

urlpatterns = [
    path("", include("apps.articles.urls", namespace="articles")),
    path("account/", include("apps.account.urls", namespace="account")),
    path("auth/", include("apps.authorization.urls", namespace="auth")),
    path("admin/", admin.site.urls, name="admin"),
    path("comments/", include("apps.comments.urls", namespace="comments")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("upload/", login_required(upload), name="ckeditor_upload"),
    path("", include("social_django.urls", namespace="social")),
    path("moderator/", include("apps.moderator.urls", namespace="moderator")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/articles/includes/modals/article_complain.html
{% load static %}
{% load my_tags %}
<div class="modal fade" id="art-complain-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content"  style="max-width: 350px">
            <div class="text-center">
                <h6 class="modal-title mt-3">Причина жалобы на статью</h6>
            </div>
            <div class="complains-modals">
                <form class="" action="{% url 'moderator:send_complain_to_article' article.pk %}" method="post"
                      enctype="multipart/form-data">
                    <div class="mx-4 mt-2">
                        {% csrf_token %}
                        {{ form_complain.as_p }}
                    </div>
                    <div style="display: flex; justify-content: space-around; margin-bottom: 15px">
                        <div>
                            <button style="width:100px" type="reset" class="btn btn-sm btn-success" data-dismiss="modal">Назад</button>
                        </div>
                        <div>
                            <input style="width:100px" type="submit" value="Отправить" class="btn btn-sm btn-danger">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

templates/articles/includes/modals/comment_complain.html
{% load static %}
{% load my_tags %}
<div class="modal fade" id="art-complain-com-modal" tabindex="-1" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content"  style="max-width: 350px">
            <div class="text-center">
                <h6 class="modal-title mt-3">Причина жалобы на комментарий</h6>
            </div>
            <div class="complains-modals">
                <form class="" action="{% url 'moderator:send_complain_to_comment' comment.id article.pk %}"
                      method="post"
                      enctype="multipart/form-data">
                    <div class="mx-4 mt-2">
                        {% csrf_token %}
                        {{ form_complain.as_p }}
                    </div>
                    <div style="display: flex; justify-content: space-around; margin-bottom: 15px">
                        <div>
                            <button style="width:100px" type="reset" class="btn btn-sm btn-success" data-dismiss="modal">Назад</button>
                        </div>
                        <div>
                            <input style="width:100px" type="submit" value="Отправить" class="btn btn-sm btn-danger">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

templates/articles/includes/modals/inc_comment_complain.html
{% load static %}
{% load my_tags %}
<div class="modal fade" id="art-complain-inccom-modal" tabindex="-1" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content"  style="max-width: 350px">
            <div class="text-center">
                <h6 class="modal-title mt-3">Причина жалобы на комментарий</h6>
            </div>
            <div class="complains-modals">
                <form class="" action="{% url 'moderator:send_complain_to_comment' child_comment.id article.pk %}"
                      method="post"
                      enctype="multipart/form-data">
                    <div class="mx-4 mt-2">
                        {% csrf_token %}
                        {{ form_complain.as_p }}
                    </div>
                    <div style="display: flex; justify-content: space-around; margin-bottom: 15px">
                        <div>
                            <button style="width:100px" type="reset" class="btn btn-sm btn-success" data-dismiss="modal">Назад</button>
                        </div>
                        <div>
                            <input style="width:100px" type="submit" value="Отправить" class="btn btn-sm btn-danger">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

templates/articles/includes/modals/repeat_send_email.html
<!--Модальное окно запроса на повторную отправку почты-->
<div class="modal first-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="text-center my-3">
                <h5 class="modal-title">Отправка почты</h5>
                <button style="position: absolute; right: 10px; top: 14px" type="button" class="btn-close"
                        data-dismiss="modal" aria-label="Close"></button>
                </button>
            </div>
            <div class="text-center my-4">
                <p>Отправить письмо повторно?</p>
            </div>
            <div class="modal-footer" style="justify-content: space-around">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <a href="{% url 'auth:send' user.pk %}">
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".second-modal">
                        Отправить
                    </button>
                </a>
            </div>
        </div>
    </div>
</div>

templates/articles/includes/modals/search_form.html
{% load static %}

<div class="modal fade" id="search-modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="search-h">
                <div>
                    <h5>Введите параметры поиска</h5>
                    <button style="position: absolute; right: 10px; top: 14px" type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
                </div>
            </div>
            <div class="form-search" style="margin: 10px">
                <form style="display: flex; flex-direction: column" class="search" role="search"
                      id="search-articles-form"
                      method="GET"
                      action="{% url 'articles:search_articles' 1 %}">
                    <input class="form-control input-search" type="text" placeholder="введите запрос"
                           aria-label="Search" name="search" value="{{ search_query }}">
                    <br>
                    <div class="search-h">
                        <div>
                            <h6>По дате публикации</h6>
                        </div>
                    </div>
                    <div class="btn-group mx-md-4" role="group" aria-label="Basic radio toggle button group">
                        <input type="radio" class="btn-check" name="searchdate" value="all" id="searchdate1" autocomplete="off"
                               checked>
                        <label class="btn btn-outline-secondary" for="searchdate1">Все</label>

                        <input type="radio" class="btn-check" name="searchdate" value="month" id="searchdate2" autocomplete="off">
                        <label class="btn btn-outline-primary" for="searchdate2">Месяц</label>

                        <input type="radio" class="btn-check" name="searchdate" value="week" id="searchdate3" autocomplete="off">
                        <label class="btn btn-outline-primary" for="searchdate3">Неделя</label>

                        <input type="radio" class="btn-check" name="searchdate" value="today" id="searchdate4" autocomplete="off">
                        <label class="btn btn-outline-primary" for="searchdate4">Сегодня</label>
                    </div>
                    <div class="search-h">
                        <div>
                            <h6>По оценкам</h6>
                        </div>
                    </div>
                    <div class="btn-group mx-5" role="group" aria-label="Basic radio toggle button group">
                        <input type="radio" class="btn-check" name="searchrate" value="any" id="searchrate1" autocomplete="off"
                               checked>
                        <label class="btn btn-outline-secondary" for="searchrate1">Любые</label>

                        <input type="radio" class="btn-check" name="searchrate" value="positive" id="searchrate2" autocomplete="off">
                        <label class="btn btn-outline-success" for="searchrate2">Положительные</label>
                    </div>
                    <div class="search-h">
                        <div>
                            <h6>По статьям (все по умолчанию)</h6>
                        </div>
                    </div>
                    <div class="btn-group mx-md-3" role="group" aria-label="Basic checkbox toggle button group">
                        <input type="checkbox" class="btn-check" name="hubscheck" value="Разработка" id="hubcheck1" autocomplete="off">
                        <label class="btn btn-outline-dark" for="hubcheck1">Разработка</label>

                        <input type="checkbox" class="btn-check" name="hubscheck" value="Дизайн" id="hubcheck2" autocomplete="off">
                        <label class="btn btn-outline-dark" for="hubcheck2">Дизайн</label>

                        <input type="checkbox" class="btn-check" name="hubscheck" value="Маркетинг" id="hubcheck3" autocomplete="off">
                        <label class="btn btn-outline-dark" for="hubcheck3">Маркетинг</label>

                        <input type="checkbox" class="btn-check" name="hubscheck" value="Научпоп" id="hubcheck4" autocomplete="off">
                        <label class="btn btn-outline-dark" for="hubcheck4">Научпоп</label>
                    </div>
                    <br>
                    <button type="submit" class="btn btn-dark" style="margin: 20px 100px">Поиск</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/articles/includes/modals/success_send_email.html
<!--Модальное окно подтверждения повторной отправки почты-->
<div class="modal second-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="text-center my-3">
{#                <h5 class="modal-title">Отправка почты</h5>#}
                <button style="position: absolute; right: 10px; top: 14px" type="button" class="btn-close"
                        data-dismiss="modal" aria-label="Close"></button>
                </button>
            </div>
            <div class="text-center my-5">
                <p>Письмо повторно отправлено</p>
            </div>
            <div class="modal-footer" style="justify-content: space-around">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>